mediaplayer/README.md, mediaplayer/mediaplayer
Also:
- refactoring, making the script more reusable
- mpd support is obtained with `mpc`
Recreated PR from https://github.com/vivien/i3blocks/pull/126.
=> mediaplayer: add support for mpd

CONTRIBUTING.md
This is an initial proposal of what the contributing guidelines should be. It is geared towards being inviting to newcomers. Request for comments.
=> Setup initial draft of contributing guidelines

batterybar/batterybar
Hello!
Really cool blocklet. I feel it was missing the time remaining value, which the main battery blocklet has, so here's my pull request.
Cheers
=> Batterybar: add time remaining on click

apt-upgrades/README.md, apt-upgrades/apt-upgrades, usb/README.md, usb/usb.py
Two commits, one for each blocklet.
=> apt-upgrades, usb: minor maintenance and new config options

apt-upgrades/README.md, apt-upgrades/apt-upgrades, apt-upgrades/i3blocks.conf, bandwidth/README.md, bandwidth/bandwidth
There are no functional changes in either commit. These just clear up the source and fix/add some documentation.
=> apt-upgrades and bandwidth documentation and source formatting

README.md, keyindicator/README.md, openvpn/README.md, temperature/README.md
Fixes https://github.com/vivien/i3blocks-contrib/issues/22
=> Use $SCRIPT_DIR instead of ./ for generic script locations

apt-upgrades/apt-upgrades, usb/README.md, usb/usb.py
I've added command line configuration for the usb script and used `[[` instead of `[` in the apt-upgrades script.
=> usb and apt-upgrades maintenance

key_layout/key_layout
Minimizing the pipes, and system calls. There was only awk and no bash.
=> key_layout optimization

monitor_manager/monitor_manager.py
Fixes https://github.com/vivien/i3blocks-contrib/issues/56
=> Fix broken duplicate functionality

bandwidth2/README.md
=> Minor: MarkDown compatible

arch-update/arch-update.py
option `-H/--hide`: produces no output if no updates available
@snowiow: Since this is completely your work up to now, you might want to add your two cents about this change.
=> arch-update: add --hide option

arch-update/README.md, arch-update/arch-update.py
Take regular expressions to watch for. Matching updateable items are
listed in brackets in the output.
=> arch-update: add --watch option

volume/README.md, volume/volume
- check if command `pulseaudio` exists
- check if pulse is running
Fixes vivien/i3blocks#236
Fixes vivien/i3blocks#201
Replaces original PR vivien/i3blocks#237
=> volume: don't check for pulse via lsmod but command

calendar/README.md, calendar/calendar
@qw3ry these changes are completely backwards compatible, but maybe you still want to check them.
=> calendar: added options for format, width and height

calendar/README.md, calendar/calendar
Follow-up to #135 for the next branch, as promised. (Finally… sorry for the delay.)
_I will also take care of a few more blocks (esp. the ones I created or modified) in the (hopefully) near future._
=> calendar: use injected environment variables

calendar/README.md, calendar/calendar
=> calendar: add short format option

arch-update/README.md, arch-update/arch-update
=>  arch-update: use injected environment variables

shutdown_menu/shutdown_menu
Fixed a small bug introduced by commit 51aaa14 which prevented the colors from showing properly with rofi.
=> Fixed a color/theme bug in shutdown_menu

bandwidth2/README.md, bandwidth2/bandwidth2.c
Two commits, 2 fixes, 1 feature.
One fix is to make space padding work when a LABEL is specified.  The feature is to add support for SI units.  And the other fix is to make the amount of padding correct for non-SI units.
More details are in the individual commits' messages.
=> bandwidth2: fix padding and add SI units

cpu_util_detailed/cpu_util_detailed
=> Fix shebang

CONTRIBUTING.md, volume-pulseaudio/README.md
* remove trailing whitespace in `CONTRIBUTING.md`
* fix typo in `volume-pulseaudio/README.md`
=> Small fixes in CONTRIBUTING.md and volume-pulseaudio/README.md

usb/usb
=> usb: avoid parsing lsblk's pretty-printing

timer_and_stopwatch/timer_and_stopwatch
Little change to make the code more modern.
=> timer_and_stopwatch: conditional expression to check `time` variable is set

taskw/README.md, taskw/i3blocks.conf, taskw/taskw
Code has also been significantly refactored.
=> taskw: Add several new config options and timewarrior integration

config.example
Complete doc here: https://github.com/altdesktop/playerctl#selecting-players-to-control
=> Better document playerctl control

battery2/battery2
Honor user overwrites, fallback to previously hard-coded colors.
=> [battery2] Make colors configurable
