- mediaplayer/mediaplayer
There was a small error in the previous commit: if mpc executed correctly but wasn't playing anything, then the script would output a blank string -- instead of try to search for other players.
> mediaplayer: fix wrong if/else

- mediaplayer/mediaplayer
Some players (like spotify) have a little delay between changing the current song and exposing the new song's data to DBUS. Waiting an small amount of time (10ms) between issuing the `next` command and retrieving the current song metadata fixed this.
The `buttons` subroutine call was also moved before the `metadata` call in order to allow the new data to be retrieved.
Please note this uses `Time::HiRes`, but it's an standard perl library since 5.8, so it shouldn't break anything.
> mediaplayer fix for slow players, fixed a bug which caused (null) - (null) being displayed

- mediaplayer/README.md
- Specify in more details what is supported.
- List the requirement for playerctl for MPRIS
- Note about leaving instance empty.
> mediaplayer - readme additions

- mediaplayer/mediaplayer
Because of how $player_arg is defined, there is a single quote between
$BLOCK_INSTANCE and endline ($).
```perl
$player_arg = "--player='cmus'";
```
> Removed endline ($) to make cmus work

- mediaplayer/mediaplayer
The buttons work the same as the other media player types.
> mediaplayer: Add click controls for cmus

- bandwidth/bandwidth
MBytes are wrongly displayed as Mbits. This PR removes the division by 8 so that it prints MB as MB.
> Fix megabyte display in bandwidth blocklet

- bandwidth/README.md
- bandwidth/bandwidth
Fixes a bug where the up/down arrows don't display properly if your pango is up to date.
> bandwidth: explicitly tell pango to use FontAwesome

- mediaplayer/README.md
You don't have to read the code every time you try to see what `mediaplayer` does.
> mediaplayer: add documentation for mouse clicks

- keyindicator/README.md
- keyindicator/keyindicator
I wanted this script block to show nothing, rather than a grayed out CAPS/NUM, when the respective switches were off. This PR adds a --hide option which does that.
I've never worked in perl before but hopefully it all looks right.
Thanks!
> keyindicator: add --hide option to not show anything if switch is off.

- keyindicator/README.md
- keyindicator/keyindicator
- Small option syntax fix in README
- Only setting background colors if explicitly specified. For users with a non-black i3bar this avoids the need to specify the background colors.
> Keyindicator: only set bg colors if specified

- volume-pulseaudio/volume-pulseaudio
[This line](https://github.com/vivien/i3blocks-contrib/blob/597a27df27/volume-pulseaudio/volume-pulseaudio#L31) is never executed because [the X was missing](https://github.com/vivien/i3blocks-contrib/pull/87/files) so I fixed it
> [volume-pulseaudio] Fix a bug which prevents users from setting custom icon for muted state

- bandwidth2/bandwidth2.c
"B/s" was only 3 chars long while "KB/s" and the others were 4 chars long. This would cause the block widget to change length all the time and was shifting the entire content of the i3bar back and forth which was very annoying.
> bandwidth2: add space before byte unit, enforce all consistent widget character length

- volume-pulseaudio/volume-pulseaudio
Currently playing audio streams do not switch automatically to new default sinks.
To move all pulse inputs when changing the default default sink (per click), I added a small function and a new new option -m
Cheers, Andrej
> volume-pulseaudio: add option -m to move all input to new default sink

- mediaplayer/mediaplayer
Added the volume control feature (already existing when using mpd/mpc) for playerctl.
I only tested it with vlc
Matthieu
> mediaplayer: add volume control for playerctl

- battery/battery
- now time left to charge is also shown
- if time is unknown, acpi shows "rate information unavailable", leading
to `(rate)` output, which is suppressed now
> battery: show time left to charge and check time validity

- battery/battery
> battery: explicitly match a time to avoid artifacts of confusing outputs

- volume-pulseaudio/README.md
The config changes for media keys in the volume-pulseaudio is missing a command to restart i3blocks. This adds it
> volume-pulseadio: add missing command in README

- config.example
The default block changed from `CPU: 100.00%` to `CPU 100.00%` in vivien/i3blocks@1209af4, i.e. the colon is not used in the label.
Replaces original vivien/i3blocks#222
> example config: (cpu_usage) fix block min_width

- gpu-load/gpu-load
Signed-off-by: merspieler <merspieler@users.noreply.github.com>
Fixed bug with wrong regex causing an error message that no GPU was found.
> Fix bug with incorrect regex

- volume/volume
I noticed on one machine (where pulse is the right option) that it's not the default output of `amixer info` and you need to explicitly specify `-D pulse`. When this command succeeds, there is no more need to check the output.
> volume: pulse-detection: explicitly try the "pulse" device

- arch-update/README.md
The `checkupdates` executable has been moved from the main pacman
package a while ago:
https://git.archlinux.org/pacman.git/commit/?id=0c99eabd50752310f42ec808c8734a338122ec86
> arch-update: updated dependency: pacman-contrib

- memory/memory
because no background color is printed
> memory: no newline after foreground color

- mediaplayer/mediaplayer
Fixes: https://github.com/vivien/i3blocks-contrib/issues/182
> mediaplayer: Fix title missing

- cpu_usage/cpu_usage
Changed the OR operation to the // default operator. This way, values can be set to 0.
> cpu_usage: Fixes: #191 - properly set defaults

- config.example
Already set by `command=$SCRIPT_DIR/$BLOCK_NAME` line
> Remove unneeded `command` line in `volume` block

- volume-pulseaudio/volume-pulseaudio
When switching devices volume-pulseaudio does not switch to the newly activated device.
As a result, it's stuck with the default device's volume, mute status etc.
That happens because volume-pulseaudio keeps track of the default device instead of the device with that has the *RUNNING* state, according to *pactl*'s output.
If no device is being used (all devices are on *SUSPENDED* state), I fall back to the default one since pactl/pacmd do not give information about which of the suspended devices is the currently used one.
Once any of them goes to *RUNNING* state though, will be picked up by the script. 
This pull request fixes this issue by grepping for the device that's on *RUNNING* state and falling back to the previous solution when all devices are suspended.
I have tested this with my …
> volume-pulseaudio: adds tracking of running device instead of the default one

- volume/volume
On some systems (e.g. NixOS, openBSD) Bash isn't located or symlinked at
`/bin/bash`. This change ensures that the correct path is used across
different operating systems.
> volume: Use '/usr/bin/env bash' as shebang

- wifi/wifi
The current `wifi` script does not show "wifi down" when the wifi device i.e. interface exists but is not active, which is a common situation on a laptop. Besides, this pull request makes the behavior of `wifi` script consistent with `iface` script.
> wifi: echo red "down" when interface exists but inactive

- README.adoc
- ssid/README.md
- ssid/i3blocks.conf
- ssid/ssid
Based on `iface` script. Uses `iw` instead of `iwconfig`, which is deprecated
according to <https://wireless.wiki.kernel.org/en/users/documentation/iw>.
As well, avoids the perl dependency, though that's not much of a benefit.
> New block: ssid:  SSID of current wifi connection

- dimmer/README.md
white space is needed in front of section titles
> dimmer: fix markdown in README

- nm-vpn/README.md
- nm-vpn/i3blocks.conf
- nm-vpn/nm-vpn
1. Fixes: #305. Look for interface type of tap|tun instead of name for connection status determination.
2. Add injected properties for init and established state colors.
3. Update README.md and i3blocks.conf according to 2.
> nm-vpn: use interface type for status, add colors, add INIT status.

- time/time
This fixes i3 bar parsing errors when the output contains characters not
in the US-ASCII encoding space like the ä in the German März (March).
Perl will by default print in US-ASCII/Latin-1 encoding, where
especially the latter can contain characters that are not valid in UTF8.
If that happens, this will cause the entire parsing of the i3blocks
output to fail in i3 bar and cause it to only show an error message.
> time: Enable time/time to print its output in UTF8

- Makefile
`make` executes Makefies in subdirectories.
`make install` does same as `make` and installs all executables under libexec directory (`$PREFIX/libexec/i3blocks/`), default PREFIX=/home/ai/.local/.
`make uninstall` removes installed executables, but not the directory itself.
This is a subject for discussion, both on how it does the job and whether it is required here at all. Note that before starting to write it I had vague ideas on how to do it and zero practice, so someone with experience and understanding may be required to review it. 
It does the job though. Currently (46ccb08) bandwidth2 fails to build (#236 supposedly fixes this), so for 'install' target '-k' flag is required: `make -k install`, or call the `do-install` target which does not depend on `build` one. 
This Makefile …
> Add global Makefile.

- volume-pulseaudio/volume-pulseaudio
When using headset in hsp/hfp currently volume-pulseaudio fails to parse volume correctly because of 'front' part of the regex match.
- Fixed parsing of volume
> volume-pulseaudio: fix volume when hsp/hfp mode on

- README.adoc
Fixes missing README entry in #304 for battery-poly.
> battery-poly: add readme entry for battery-poly in README.adoc

- volume/README.md
- volume/volume
If `NATURAL_MAPPING` is set to a non-zero value, the `-M` flag is used for `amixer`, enabling
a volume mapping more natural for the human ear, as used in alsamixer.
from AMIXER(1):
"Use the mapped volume for evaluating the percentage representation like alsamixer, to be
more natural for human ear."
The default behaviour is unchanged.
> volume: allow amixer's `-M` flag

- aur-update/README.md
- aur-update/aur-update
If you enable caching (`CACHE_UPDATES=1`), the update list will be written to a file
(given by `CACHE_PATH`). This will be read on a click to directly show the notification
without the delay caused by updating the list.
> Aur update

- aur-update/README.md
- aur-update/aur-update
More elegant solution that does not require to write a temporary file.
Needs json format, though.
> aur-update: cache updates via environment rather than a file

- gpu-load/README.md
- gpu-load/gpu-load
This add support for showing AMD based card with `radeontop` dependency.
Note that it only support 2 of 4 existing metrics because `radeontop` doesn't expose the same variable as `nvidia-settings`.
> gpu-load: support AMD based card

- timer_and_stopwatch/README.md
- timer_and_stopwatch/timer_and_stopwatch
I am not using this blocklet much, but I've used it again and realized I hardcoded `#000000` (black) as the color for the neutral background.
For a while however, I've been using a non-black i3 bar, and having the background of a blocklet black is really ugly.
This commit exposes the variable `NEUTRAL_COLOR` to specify that color; it defaults to `#000000` otherwise.
As regards the other colors (for instance the colors from green to red for the timer), which can also be not ok for users who decide to give their i3 bars an "unconvetional" coloring, I think I could in the future export something like initial color, final color, and similar.
> timer_and_stopwatch: export neutral background color

- rofi-calendar/README.md
- rofi-calendar/rofi-calendar
All changes are non-breaking, as default values for new variable are set. Details:
1. `BAR_POSITION` is added to make calendar visible for a bar on the top of the screen. This is done by specifying `anchor` variable for `rofi` command passed by the added variable. Possible further improvement is possibly passing a `$BAR_POSITION` variable from i3's `config` to `i3block.conf`.
2. `WEEK_START` simply takes advantage of the `--monday` and `--sunday` arguments of `cal` command.
`README.md` is updated to reflect the above.
> rofi-calendar: add BAR_POSITION and WEEK_START variables

- dunst/dunst
In order to follow dunst changes, dunsctl should be used now
> Switch to dunstctl because of deprecation warnings

- backlight/backlight
`xbacklight -get` (v1.2.3) shows several decimal places:
Most users aren't interested in subdecimal screen brightness, but want a rounded value:
> backlight: remove decimal places from displayed screen brightness

- disk-io/disk-io
Allows the read part to be aligned by the user. Set `ALIGN=` to do so.
> disk-io: Allow user-specified alignment

- configure
since the repo already can be built with something reassembling GNU autotools convention
```
make
make install
```
this patch aims at making it even more compatible by allowing this:
```
configure --prefix=/some/path
make
make install
```
The script doesn't do more than patching the Makefile to respect the set prefix and is **fully backwards compatible** (running `./configure` without `--prefix` is a noop).
> add configure script

- eyedropper/README.md
- eyedropper/eyedropper
- eyedropper/i3block.conf
Please let me know if you think it would be better to create a separate blocklet for the Sway version instead of configuring this one as an option.
> eyedropper: add support for Sway, and for copying to the clipboard

- battery-poly/battery-poly
I noticed div-by-zero exceptions in my ~/.xsession-errors.
> battery-poly: fix division-by-zero exception

- shutdown_menu/shutdown_menu
With the release of [rofi 1.7.0](https://github.com/davatorium/rofi/releases/tag/1.7.0), some arguments given to rofi by this script do not work anymore and it results in a badly styled window so I updated these to work with this new version.
I downgraded rofi to the previous version to see if there was any problem with previous versions and the script was working properly with my changes.
> shutdown_menu: update args for rofi 1.7.0

- bandwidth/bandwidth
Why? It seems more reliable to use /tmp, as /dev/shm may not always be
present[1].
[1]: https://superuser.com/a/45509
> Use /tmp instead of /dev/shm to store path.

- mediaplayer/mediaplayer
A small PR to redirect playerctl's stderr to /dev/null. My reason for suggesting this change is that my desktop manager was flooding my logs with messages like this:
```
/usr/lib/gdm-x-session: No players found
```
Confusingly, it turns out that if no player is active, playerctl will write "No players found" to *stderr*, and not *stdout*. Since the mediaplayer blocklet does not capture playerctl's stderr, this gets bubbled up to gdm with no indication that the source of the error is playerctl -> mediaplayer blocklet -> i3blocks. Afaik, this change to mediaplayer does not impact functionality, as redirecting stderr does not change playerctl's return code (and the mediaplayer blocklet doesn't look at playerctl's stderr anyway).
On another note, is there any interest in a more systematic …
> mediaplayer: redirect playerctl stderr to /dev/null

- volume-pipewire/README.md
volume-pipewire uses amixer, which comes in also-utils package. Without it, it's not functional.
> volume-pipewire depends on alsa-utils

- dunst/README.md
update documentation to reflect 99725fb: dunstctl is used now
> dunst: update documentation to reflect 99725fb

- dunst/README.md
- dunst/dunst
- using more efficient dict.get single-lookup
<br>
- getting rid of unnecessary remnants of 'DUNST_MUTE' environment
variable
- using `set-paused toggle` instead of manual checking and setting
`on/off`
- json payload is not created inside the state-setting function
> dunst: simplifications and cleaning

- rofi-calendar/rofi-calendar
Similar to #418, rofi-calendar was broken on rofi 1.7.0.  
I also took the liberty to remove the scrollbar and adjust the default size for what looks good on my screen. Maybe screen width could be passed as an argument from i3blocks config ?
I tested the script for rofi 1.7 and made sure the changes were backwards compatible for rofi 1.6.1.
> rofi-calendar: Update rofi call for rofi >=1.7

- volume-pipewire/README.md
The documentation made reference to signalling that wasn't in the example, I updated it so a user can just copy/paste if desired.
> Fix documentation for volume signalling

- aur-update/README.md
- aur-update/aur-update
Usage of IPV4 can be forced using `FORCE_IPV4=1`. This is useful, because the AUR API often gets timeouts with IPV6 and the call does not return.
> aur-update: add option to force IPV4 usage

- dunst/dunst
rather than the low-level Popen
> dunst: use check_output
